# Generated by Django 4.0.6 on 2022-07-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128, null=True, verbose_name='عنوان')),
                ('slug', models.CharField(max_length=128, null=True, verbose_name='پیوند یکتا')),
                ('content', models.TextField(verbose_name='متن صفحه')),
            ],
            options={
                'verbose_name': 'صفحه',
                'verbose_name_plural': 'صفحات',
            },
        ),
    ]
