# Generated by Django 4.0.6 on 2022-07-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.CharField(max_length=127, null=True, verbose_name='قیمت تخفیف'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_discount',
            field=models.BooleanField(default=False, verbose_name='آیا تخفیف فعال است؟'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=128, null=True, verbose_name='قیمت اصلی'),
        ),
    ]
