# Generated by Django 4.0.6 on 2022-07-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_size_product_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.ManyToManyField(blank=True, to='shop.size'),
        ),
    ]
